exclude: ^migrations/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
    language_version: python3.10
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        require_serial: true
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--load-plugins=pylint_django",
            "--django-settings-module=django_tournament.settings", # new
            "--ignore=manage.py",
          ]
